### PR TITLE
Dispose ConfigurationReloadToken

### PR DESCRIPTION
**Pull request by HaoK**
Merge of https://github.com/aspnet/Extensions/pull/588

### CODE REVIEW

**Comment by ajcvickers** [comment]
@HaoK So based on Chris's comments, it sounds like we shouldn't do this.

**Comment by HaoK** [comment]
Yeah I guess the issue is that we shouldn't dispose the underlying cancellation token after it fires, but we maybe should dispose the ConfigurationReloadToken as part of ConfigurationRoot's dispose: 
https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config/src/ConfigurationRoot.cs#L124

Thoughts?

**Comment by Tratcher** [comment]
Those roots would only be disposed at the end of the application, no? Yes that'd be a good idea, but I don't see how it ties back to the original bug report.

**Comment by HaoK** [comment]
I'm not sure what you are referring to in the original bug, you mean "Possible CTS leak in ConfigurationReloadToken / ConfigurationRoot" ?  If its not safe to dispose the CTS after firing, then the only thing we can do is dispose it when the root is disposed.

**Comment by Tratcher** [comment]
They implied there was a memory accrual for non-disposed tokens during the lifetime of the app. It doesn't look that that was ever confirmed.

**Comment by HaoK** [comment]
Configuration leaking was addressed via https://github.com/aspnet/Extensions/issues/861 so yeah that was  reported in other issues

**Comment by HaoK** [comment]
Closing this for now, issue remains open for tracking/discussion

**Pull request closed without merging**
