### PR TITLE
Update corefx dependencies

### PR DESCRIPTION
**Pull request by BrennanConroy**
Had to manually change the versions because of certain people being people...

These are the "officially decided on" versions we're using from the release channel.

### CODE REVIEW

**Comment by anurse** [comment]
Let's take this ASAP so we can let it settle.

**Comment by anurse** [comment]
Can we manually take this to aspnet/AspNetCore ASAP? I'd like the breaking changes resolved as quickly as possible for obvious reasons 😛.

**Comment by BrennanConroy** [comment]
😢  I guess I can

**Comment by anurse** [comment]
I mean, if the automation is working and `EveryBuild` this may just be baby-sitting :).

**Comment by dougbu** [comment]
What exactly led to the need for this manual update? I understand the reaction changes but not why the Maestro bot didn't use these versions automatically.

If this is about pulling from '.NET Core 3 Release' instead of '.NET Core 3 Dev', later CoreFx and core-setup packages will undo the changes here. We should only be using '.NET Core 3 Dev' on the master branch of any of our repos.

**Pull request merged**
