### PR TITLE
Wrapped SqlCommand and SqlDataReader in using statement

### PR DESCRIPTION
**Pull request by epignosisx**
Wrapped SqlCommand and SqlDataReader in using statement. While the implementation details of `SqlCommand` does very little in the `Dispose` method, `SqlDataReader` does seem to be doing some important cleanup.

Addresses #940

### CODE REVIEW

**Comment by Tratcher** [comment]
@muratg for triage

**Comment by muratg** [comment]
@JunTaoLuo could you take a look at this please?

**Comment by epignosisx** [comment]
Hi @JunTaoLuo now preview2 was released when do you plan to merge this? Kind of eager to test if this helps with the issues we've been having.

**Comment by JunTaoLuo** [comment]
Ah this dropped of my radar. Sorry about that.

**Comment by epignosisx** [comment]
Thanks for the help!

**Pull request merged**
