### PR TITLE
Remove Microsoft.Bcl.AsyncInterfaces dependency

### PR DESCRIPTION
**Pull request by mmitche**
This is no longer produced by corefx as of https://github.com/dotnet/corefx/pull/41270

### CODE REVIEW

**Comment by anurse** [comment]
I'm a little confused by this. We still need this dependency for `netstandard2.0` builds. Isn't this going to cause all these builds to fail now?

What's the goal here? Is it just about stopping dependency flow of this package? That makes some sense, but I think we'll need to stay on the public 3.0 GA build of this package then, not remove it entirely.

**Comment by mmitche** [comment]
> I'm a little confused by this. We still need this dependency for `netstandard2.0` builds. Isn't this going to cause all these builds to fail now?
> 
> What's the goal here? Is it just about stopping dependency flow of this package? That makes some sense, but I think we'll need to stay on the public 3.0 GA build of this package then, not remove it entirely.

No longer being produced from corefx, so we probably just need to pin to the public 3.0 GA release.  I'll do that.

**Comment by mmitche** [comment]
Should work better now.

**Comment by mmitche** [comment]
```
error NU1605: Detected package downgrade: Microsoft.Bcl.AsyncInterfaces from 1.2.0-alpha1.19504.7 to 1.0.0. Reference the package directly from the project to select a different version.
```

**Comment by anurse** [comment]
I think the baseline file may need to be updated? @aspnet/build ?

**Comment by dougbu** [comment]
Suggest pinning the package at 1.2.0-alpha1.19504.7 instead of going back to 1.0.0. (Seems likely something else in CoreFx or core-setup is referencing that version.)

**Comment by anurse** [comment]
> Suggest pinning the package at 1.2.0-alpha1.19504.7 instead of going back to 1.0.0

That's not going to work either right? It sounds like there isn't going to be a `1.2.0` GA release of the package, but we need to ship using some GA version of this package.

**Comment by mmitche** [comment]
> Suggest pinning the package at 1.2.0-alpha1.19504.7 instead of going back to 1.0.0. (Seems likely something else in CoreFx or core-setup is referencing that version.)

I think actually we just need to update the dependencies.  That version was the last time it was actually produced.

**Comment by mmitche** [comment]
That did it....any other concerns?

**Comment by dougbu** [comment]
@mmitche @Anipik @ViktorHofer @ericstj am I correct we'll need this change in 'release/3.1' as well? We have the same dependency there.

@ajcvickers @bricelam I suspect fixing things here is necessary to unblock aspnet/EntityFrameworkCore#18453.

**Comment by mmitche** [comment]
I don't think so.  I still see versions of that being produced in 3.1 as recent as the 18th.

```
PS D:\enlistments\AspNetCore-Tooling> darc get-asset --name "Microsoft.Bcl.AsyncInterfaces" --channel ".NET Core 3.1 Dev"                                                   Looking up assets with name 'Microsoft.Bcl.AsyncInterfaces' on channel '.NET Core 3.1 Dev' in the last 30 days                                                              Microsoft.Bcl.AsyncInterfaces @ 1.1.0-preview2.19518.6
Repository:    https://github.com/dotnet/corefx
Branch:        release/3.1
Commit:        58dbf71fd0d9593c4bf8a1ecb2d5d4ff6882e782
Build Number:  20191018.6
Date Produced: 10/18/2019 2:13 PM
Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=393631
BAR Build Id:  31902
Channels:
- .NET Core 3.1 Dev
Locations:
- https://dev.azure.com/dnceng/internal/_apis/build/builds/393631/artifacts (Container)
- https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json (NugetFeed)
- https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet3.1/nuget/v3/index.json (NugetFeed)
```

**Comment by ViktorHofer** [comment]
Right, we removed those packages only in master which currently targets 5.0. No need to react in 3.x.

**Pull request merged**
