### PR TITLE
Add Microsoft.Extensions.Logging.AzureAppServices to patch

### PR DESCRIPTION
**Pull request by BrennanConroy**
@aspnet/build

### CODE REVIEW

**Comment by natemcmaster** [comment]
Retarget this PR to release/2.2

**Comment by dougbu** [comment]
@BrennanConroy you need (parts of) @natemcmaster's PR #1405 plus additional NuGetPackageVerifier.json changes to get the package verification working.

**Comment by dougbu** [comment]
@anurse @natemcmaster does this need to go to Shiproom (in email)?

**Comment by anurse** [comment]
> does this need to go to Shiproom (in email)?

I presume so. I'll send an email.

**Comment by anurse** [comment]
@BrennanConroy do you know what is needed to update the Site Extension? Could you sync up with @pakrym if necessary to do so? We need to try and get any code changes for that in tomorrow (4/12).

**Comment by BrennanConroy** [comment]
I don't, but I'd like to find out.

**Comment by anurse** [comment]
Would you though? Would you?

My first assessment is that we need to flow Extensions in to AspNetCore before we can do it, and then update the version in [Microsoft.AspNetCore.AzureAppServicesIntegration.csproj](https://github.com/aspnet/AspNetCore/blob/922512a9fb5ca16c73b75c16c946d6ec92dd81f9/src/Azure/AzureAppServicesIntegration/src/Microsoft.AspNetCore.AzureAppServicesIntegration.csproj#L15). It mostly flows forward from there but I'm sure there's a quirk or two.

**Comment by BrennanConroy** [comment]
>My first assessment is that we need to flow Extensions in to AspNetCore before we can do it

Yeah, looks like we need to merge this ASAP if we want to be done today.

**Comment by dougbu** [comment]
There's no "flow" needed here. Extensions is **not** an AspNetCore submodule in 2.x and a ProdCon will push what's needed into AspNetCore.

**Comment by BrennanConroy** [comment]
>ProdCon will push what's needed into AspNetCore

That is the flow.

Does the PR to AspNetCore happen quickly or can we force it to be quick?

**Comment by natemcmaster** [comment]
In 2.2, there is no PR to AspNetCore. The next time we trigger a 2.2 build, AspNetCore will get updated automatically.

**Comment by dougbu** [comment]
> Does the PR to AspNetCore happen quickly or can we force it to be quick?

...
>  The next time we trigger a 2.2 build, AspNetCore will get updated automatically.

There has not been an attempted official build of 2.x for this month. If we need one immediately after this PR is merged, @mmitche can kick it off. Please let him and us know.

**Comment by mmitche** [comment]
@dougbu Already in progress.

**Comment by anurse** [comment]
We still need to ensure that it actually lands **in the site extension**. So the build will automatically flow the new dependency versions into the AspNetCore build?

**Comment by BrennanConroy** [comment]
I'll be making a PR when it's available.

**Comment by vivmishra** [comment]
Approved for 2.2.5

**Pull request merged**
