### PR TITLE
Prevent dublicating hosted services registered with AddHostedService

### PR DESCRIPTION
**Pull request by Chakrygin**
`AddSingleton` replaced with `TryAddEnumerable`

#1078

### CODE REVIEW

**Comment by Tratcher** [comment]
Fixed the CI with https://github.com/aspnet/Extensions/pull/1082#event-2122746041, please rebase.

**Comment by Chakrygin** [comment]
I'm not sure I did it right

**Comment by Tratcher** [comment]
Thanks

**Comment by ahdung** [comment]
`Add` is a clear behavior, you should do it for `TryAdd`.

**Pull request merged**
