### PR TITLE
[2.1+] Add robustness to Config FileProvider tests

### PR DESCRIPTION
**Pull request by ajcvickers**
Specifically:
* Don't let current thread continue until file system change is visible
* Retry when waiting for notifications

Fixes: https://github.com/aspnet/AspNetCore-Internal/issues/1319

### CODE REVIEW

**Comment by ajcvickers** [comment]
@natemcmaster Can we merge test changes for 2.1 and 2.2 here?

**Comment by natemcmaster** [comment]
I believe test-only fixes to 2.x branches is okay, but we usually check with @Eilon just be sure.

**Comment by ajcvickers** [comment]
@natemcmaster I actually was just asking if this was the right place for 2.1 fixes.

**Comment by natemcmaster** [comment]
Yes, this is the right place for 2.1 fixes.

**Comment by ajcvickers** [comment]
@HaoK Finally have these passing on 2.1--I did the work initially on 3.0, but figured we should backport. Can you review? Also see https://github.com/aspnet/Extensions/issues/617

**Pull request merged**
