### PR TITLE
Implement infrastructure changes to support ProdCon v1

### PR DESCRIPTION
**Pull request by natemcmaster**
This duplicates a simplified version of infrastructure from aspnet/AspNetCore into this repo. This allows us to pull the aspnet/Extensions submodule out of aspnet/AspNetCore and treat it as an independent leg of the build.

### CODE REVIEW

**Comment by natemcmaster** [comment]
⌚️ waiting until ProdCon changes are ready to merge.

**Comment by natemcmaster** [comment]
ProdCon changes aren't ready to merge yet. However, I'd like to merge this now so I can move forward with other repo merges. We can do this without affecting 2.1.6 builds by pausing the automation which updates submodules in aspnet/AspNetCore, and by holding off on https://github.com/aspnet/AspNetCore/pull/3671. Sound okay?

cc @muratg

**Comment by Eilon** [comment]
So if we need a 2.1.6 last minute rebuild we'd be OK? If so, go for it.

**Comment by natemcmaster** [comment]
Correct. And yes, we will definitely need a last minute 2.1.6 build. I'll update TeamCity so this merge doesn't affect 2.1.6.

**Pull request merged**
