### PR TITLE
Port HttpClient Factory test fixes

### PR DESCRIPTION
**Pull request by rynowak**
Porting some improvements to flaky tests that were made in master

### CODE REVIEW

**Comment by rynowak** [comment]
Are the test failures known? I didn't do that. 

```
Microsoft.Extensions.Caching.Memory.Tests.Microsoft.Extensions.Caching.Memory.CapacityTests.DoNotAddIfSizeOverflows
Assert.True() Failure
Expected: True
Actual:   False
```

**Comment by HaoK** [comment]
I'm not sure I have seen some random caching tests fail occasionally on my pr runs too (mostly on linux) but that one doesn't seem familiar, @natemcmaster @Tratcher any ideas?

For example this one failed for me the other day in a PR run too, but its not the same test 

https://dnceng.visualstudio.com/public/_build/results?buildId=56490

```
2018-12-11T23:33:05.3736663Z   Failed   Microsoft.Extensions.Caching.Memory.CapacityTests.AddingReplacementWhenTotalSizeExceedsCapacityDoesNotUpdateRemovesOldEntryAndTriggersCompaction
2018-12-11T23:33:05.3736966Z   Error Message:
2018-12-11T23:33:05.3737156Z    Assert.True() Failure
2018-12-11T23:33:05.3737272Z   Expected: True
2018-12-11T23:33:05.3737420Z   Actual:   False
2018-12-11T23:33:05.3737545Z   Stack Trace:
```

**Comment by Tratcher** [comment]
Some of the tests that depend on background threads have become flaky in the mondo repo because there's a lot more tests run concurrently. We'll have to revisit their synchronization and timeouts.

**Pull request merged**
