### PR TITLE
Return IServiceCollection in TryAdd methods

### PR DESCRIPTION
**Pull request by Kahbazi**
Addresses #1768

### CODE REVIEW

**Comment by Eilon** [comment]
FYI this is a breaking change: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md#signatures

Breaking changes are permitted in major versions (which this is), but need to be scrutinized.

**Comment by Kahbazi** [comment]
This technically won't change return type, only adds one since they were all void and no code would be break with this update. Can we consider an exception here?

**Comment by Eilon** [comment]
The return 'type' was `void` and is now something else. Yes, `System.Void` is a real type! Such a change is not *likely* to break code, but it certainly *can*. I'm not sure if it can break binary compatibility, but it can definitely cause compilation changes/breaks and runtime changes/breaks.

Ultimately the question that will be asked is: does the benefit of this change outweigh the cost.

**Comment by davidfowl** [comment]
We're not going to make this breaking change.

**Pull request closed without merging**
