### PR TITLE
Prepare the repo for the 2.1.7 patch

### PR DESCRIPTION
**Pull request by natemcmaster**
Changes:
* Update targets to correctly import Baseline.props after setting PackageId
* Add error checking to ensure the baseline is up to date
* Bump version to 2.1.7
* Update BuildTools to include signcheck
* Update tests to use the 2.1.6 runtime

### CODE REVIEW

**Comment by natemcmaster** [comment]
+ added a document on steps required to prepare a servicing update for this repo.

**Comment by Eilon** [comment]
Hmm didn't I just see these changes in the Extensions PR? Maybe it accidentally included more than you intended?

**Comment by natemcmaster** [comment]
Oh, yeah, the changes in https://github.com/aspnet/Extensions/pull/483 are based on this PR.

**Comment by Eilon** [comment]
OK well I already saw those so I'll sign off 😄

**Pull request merged**
