### PR TITLE
Update dependencies files

### PR DESCRIPTION
**Pull request by natemcmaster**
Ran darc manually to get caught up.

### CODE REVIEW

**Comment by natemcmaster** [comment]
Tests failed on macOS with

```
2019-01-08T20:32:45.3006800Z   Total tests: Unknown. Passed: 3322. Failed: 0. Skipped: 109.
2019-01-08T20:32:45.3007010Z   Test Run Aborted.
```

This often happens when there are memory issues with unmanaged code. Retrying the test run to see if it is consistent.

**Comment by natemcmaster** [comment]
Failures are consistent. I've opened https://github.com/dotnet/corefx/issues/34434 and made it a partner-blocking issue.

**Comment by natemcmaster** [comment]
Still waiting on a new build of core-setup which contains https://github.com/dotnet/corefx/pull/34438

**Comment by natemcmaster** [comment]
Updated to pin System.Threading.Tasks.Extensions to 4.5.2, per https://github.com/dotnet/corefx/issues/34473

**Comment by natemcmaster** [comment]
Blocked on https://github.com/dotnet/core-setup/pull/4931

**Comment by benaadams** [comment]
Bot version just passed? https://github.com/aspnet/Extensions/pull/933

**Comment by natemcmaster** [comment]
Closing in favor of https://github.com/aspnet/Extensions/pull/933

**Pull request closed without merging**
