### PR TITLE
Remove merge artifact, fix CTS leak

### PR DESCRIPTION
**Pull request by berdon**
Summary of the changes (Less than 80 chars)
- Fix some merge artifacts in master's .sln
- Dispose of revolving ConfigurationReloadToken's underlying CancellationTokenSource

Addresses #587

### CODE REVIEW

**Comment by ajcvickers** [comment]
@HaoK Does this look like a good change to take?

**Comment by HaoK** [comment]
The dispose change looks good

**Comment by ajcvickers** [comment]
@HaoK Okay, let's merge it then.

**Comment by HaoK** [comment]
Replaced by https://github.com/aspnet/Extensions/pull/1462

**Pull request closed without merging**
